[2025-02-05T06:31:47.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dag.execute_remote_script manual__2025-02-05T03:46:37.068840+00:00 [queued]>
[2025-02-05T06:31:47.761+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dag.execute_remote_script manual__2025-02-05T03:46:37.068840+00:00 [queued]>
[2025-02-05T06:31:47.761+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2025-02-05T06:31:47.765+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): execute_remote_script> on 2025-02-05 03:46:37.068840+00:00
[2025-02-05T06:31:47.767+0000] {standard_task_runner.py:57} INFO - Started process 427 to run task
[2025-02-05T06:31:47.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_dag', 'execute_remote_script', 'manual__2025-02-05T03:46:37.068840+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp6pb0sj8x']
[2025-02-05T06:31:47.769+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask execute_remote_script
[2025-02-05T06:31:47.774+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-05T06:31:47.785+0000] {task_command.py:415} INFO - Running <TaskInstance: example_dag.execute_remote_script manual__2025-02-05T03:46:37.068840+00:00 [running]> on host 3849bfb82152
[2025-02-05T06:31:47.812+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_dag' AIRFLOW_CTX_TASK_ID='execute_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T03:46:37.068840+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T03:46:37.068840+00:00'
[2025-02-05T06:31:47.812+0000] {ssh.py:135} INFO - Creating ssh_client
[2025-02-05T06:31:47.824+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-02-05T06:31:47.828+0000] {base.py:73} INFO - Using connection ID 'ssh-server' for task execution.
[2025-02-05T06:31:47.829+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-02-05T06:31:47.860+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2025-02-05T06:31:47.917+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2025-02-05T06:31:47.918+0000] {ssh.py:475} INFO - Running command: bash /script/date_print.sh
[2025-02-05T06:31:48.017+0000] {ssh.py:521} INFO - 当前时间是: Wed Feb  5 06:31:48 UTC 2025
[2025-02-05T06:31:48.033+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_dag, task_id=execute_remote_script, execution_date=20250205T034637, start_date=20250205T063147, end_date=20250205T063148
[2025-02-05T06:31:48.078+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-05T06:31:48.085+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
